ARM/dts: atlas7: fix build error caused  by sd commit
fixed:
  DTC     arch/arm/boot/dts/atlas7-evb.dtb
ERROR (duplicate_label): Duplicate label 'sd2' on /axi/pci-iobg/sdhci@14200000 and /axi/peri-iobg/pci-iobg/sdhci@14200000
ERROR: Input tree has errors, aborting (use -f to force output)
make[3]: *** [arch/arm/boot/dts/atlas7-evb.dtb] Error 2
make[2]: *** [dtbs] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/home/ASIA/bs14/atlas6-3.x/kernel-1/linux-stable'
make: *** [kernel] Error 2

Signed-off-by: Barry Song <Baohua.Song@csr.com>