usb: gadget: fix build errors after Gadget directory cleanup
Andrzej Pietrasiewicz's "usb: gadget: Gadget directory cleanup" causes
kernel build issues in some build systems like buildroot.
"
make[6]: *** [drivers/usb/gadget/legacy/mass_storage.o] Error 1
make[6]: *** Waiting for unfinished jobs....
drivers/usb/gadget/epautoconf.c:23:26: fatal error: gadget_chips.h: No such file or directory  #include "gadget_chips.h"
                          ^
compilation terminated.
make[5]: *** [drivers/usb/gadget/epautoconf.o] Error 1
make[5]: *** Waiting for unfinished jobs....
drivers/usb/gadget/function/f_mass_storage.c:222:26: fatal error: gadget_chips.h: No such file or directory  #include "gadget_chips.h"
                          ^
compilation terminated.
make[6]: *** [drivers/usb/gadget/function/f_mass_storage.o] Error 1
make[6]: *** Waiting for unfinished jobs....
drivers/usb/gadget/legacy/ether.c:26:21: fatal error: u_ether.h: No such file or directory  #include "u_ether.h"
                     ^
compilation terminated.
make[6]: *** [drivers/usb/gadget/legacy/ether.o] Error 1
make[5]: *** [drivers/usb/gadget/legacy] Error 2 In file included from drivers/usb/gadget/function/rndis.h:19:0,
                 from drivers/usb/gadget/function/rndis.c:42:
drivers/usb/gadget/function/u_ether.h:23:26: fatal error: gadget_chips.h: No such file or directory  #include "gadget_chips.h"
                          ^
compilation terminated.
make[6]: *** [drivers/usb/gadget/function/rndis.o] Error 1 In file included from drivers/usb/gadget/function/u_ether.c:25:0:
drivers/usb/gadget/function/u_ether.h:23:26: fatal error: gadget_chips.h: No such file or directory  #include "gadget_chips.h"
"

PWD doesn't have to be equal with source codes tree. this patch removes
these redundant PWD and fixes build issues.

Change-Id: I1974b4a9114c30d73c2c5bb862a85d82afdab8d1
Signed-off-by: Barry Song <Baohua.Song@csr.com>