mmc:sirf:host Fix coding style errors in previouse commit There are several coding style errors in 5d6394969c5022447596fa1bd6b85b69cf6b24e9 which may cause the patch can not be cherry-picked.Fix the errors here.
ERROR: "foo* bar" should be "foo *bar"
#27: FILE: drivers/mmc/host/sdhci.c:723:
+	struct page* firstpage;

ERROR: "foo* bar" should be "foo *bar"
#35: FILE: drivers/mmc/host/sdhci.c:728:
+		void* page_base;

WARNING: Missing a blank line after declarations
#36: FILE: drivers/mmc/host/sdhci.c:729:
+		void* page_base;
+		partlen = 0;

WARNING: line over 80 characters
#39: FILE: drivers/mmc/host/sdhci.c:732:
+			pagenum = (PAGE_SIZE + sg[i].length + 
sg[i].offset - 1)/PAGE_SIZE;

WARNING: braces {} are not necessary for single statement blocks
#44: FILE: drivers/mmc/host/sdhci.c:737:
+				if (j == 0) {
+					sgbuf += sg[i].offset;
+				}

WARNING: line over 80 characters
#47: FILE: drivers/mmc/host/sdhci.c:740:
+				partlen = min(length, (PAGE_SIZE - 
(unsigned int)sgbuf%PAGE_SIZE));

ERROR: space required after that close brace '}'
#53: FILE: drivers/mmc/host/sdhci.c:746:
+		}else {

ERROR: "foo* bar" should be "foo *bar"
#70: FILE: drivers/mmc/host/sdhci.c:765:
+	struct page* firstpage;

ERROR: "foo* bar" should be "foo *bar"
#78: FILE: drivers/mmc/host/sdhci.c:770:
+		void* page_base;

WARNING: Missing a blank line after declarations
#79: FILE: drivers/mmc/host/sdhci.c:771:
+		void* page_base;
+		partlen = 0;

WARNING: line over 80 characters
#82: FILE: drivers/mmc/host/sdhci.c:774:
+			pagenum = (PAGE_SIZE + sg[i].length + 
sg[i].offset - 1)/PAGE_SIZE;

WARNING: braces {} are not necessary for single statement blocks
#87: FILE: drivers/mmc/host/sdhci.c:779:
+				if (j == 0) {
+					sgbuf += sg[i].offset;
+				}

WARNING: line over 80 characters
#90: FILE: drivers/mmc/host/sdhci.c:782:
+				partlen = min(length, (PAGE_SIZE - 
(unsigned int)sgbuf%PAGE_SIZE));

ERROR: space required after that close brace '}'
#96: FILE: drivers/mmc/host/sdhci.c:788:
+		}else {

total: 6 errors, 8 warnings, 92 lines checked

Change-Id: Id35e19f466fd6a324c6b782d77d0146de447403a
Signed-off-by: weijun yang <york.yang@csr.com>