misc: a7ca_bt: make it depend on ARCH_SIRF
this fixes build issues for non-csr platform:
a7ca_bt.c:138: undefined reference to `sirfsoc_rtc_iobrg_readl'

Change-Id: Ib6bd34461ee52e31bece71f35bb4135fa885060d
Signed-off-by: Barry Song <baohuas@codeaurora.org>